version: '3.8'
services:

  postgres-opex:
    image: ghcr.io/opexdev/postgres-opex
    build: docker-images/postgres

  wallet:
    build: wallet/wallet-app
    volumes:
      - "./drive-key.json:/drive-key.json"
  vault:
    build: docker-images/vault

  bc-gateway:
    build: bc-gateway/bc-gateway-app
