ALTER TABLE devices
    ADD COLUMN IF NOT EXISTS brand VARCHAR(100),
    ADD COLUMN IF NOT EXISTS model VARCHAR(100),
    ADD COLUMN IF NOT EXISTS platform VARCHAR(50),
    ADD COLUMN IF NOT EXISTS agent VARCHAR(255),
    ADD COLUMN IF NOT EXISTS build_number INTEGER;