#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_READ_ONLY_USER WITH ENCRYPTED PASSWORD '$POSTGRES_READ_ONLY_PASSWORD';
	GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_READ_ONLY_USER;
	GRANT USAGE ON SCHEMA public TO $POSTGRES_READ_ONLY_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO $POSTGRES_READ_ONLY_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON SEQUENCES TO $POSTGRES_READ_ONLY_USER;
EOSQL
