package co.nilin.opex.matching.engine.ports.kafka.submitter.service

import co.nilin.opex.matching.engine.core.eventh.events.TradeEvent
import co.nilin.opex.matching.engine.core.inout.InputKafkaMetadata
import co.nilin.opex.matching.engine.core.model.PreparedCommandResult
import co.nilin.opex.matching.engine.core.spi.OrderBookTransitionPublisher
import org.apache.kafka.clients.consumer.OffsetAndMetadata
import org.apache.kafka.common.TopicPartition
import org.springframework.kafka.core.KafkaTemplate
import org.springframework.stereotype.Component
import org.springframework.util.concurrent.ListenableFuture
import java.util.concurrent.ExecutionException
import co.nilin.opex.matching.engine.core.model.Pair
@Component
class OrderBookTransitionSubmitter(
    private val kafkaTemplate: KafkaTemplate<String, Any>
) : OrderBookTransitionPublisher {
    override suspend fun publish(
        prepared: PreparedCommandResult,
        inputMetadata: InputKafkaMetadata
    ) {
        check(kafkaTemplate.isTransactional) {
            "KafkaTemplate is not configured for transactions"
        }

        kafkaTemplate.executeInTransaction { operations ->
            val futures =
                mutableListOf<ListenableFuture<*>>()

            /*
             * Publish every public event generated by this command.
             */
            prepared.events.forEach { event ->
                val key = pairKey(event.pair)

                futures += operations.send(
                    eventsTopic(event.pair),
                    key,
                    event
                )

                /*
                 * Preserve your current behavior:
                 * TradeEvent is sent to both the general events topic
                 * and the dedicated trades topic.
                 */
                if (event is TradeEvent) {
                    futures += operations.send(
                        tradesTopic(event.pair),
                        key,
                        event
                    )
                }
            }

            /*
             * Publish the durable order-book delta only when
             * the command changed order-book state.
             */
            prepared.stateTransition?.let { transition ->
                futures += operations.send(
                    ORDER_BOOK_CHANGELOG_TOPIC,
                    pairKey(prepared.pair),
                    transition.preparedBook
                )
            }

            /*
             * Wait for all Kafka sends.
             *
             * If one send fails, this throws and executeInTransaction()
             * aborts the complete transaction.
             */
            waitForAll(futures)

            /*
             * Commit the consumed input record's next offset
             * in the same Kafka transaction.
             */
            val offsets = mapOf(
                TopicPartition(
                    inputMetadata.topic,
                    inputMetadata.partition
                ) to OffsetAndMetadata(
                    inputMetadata.nextOffset
                )
            )

            operations.sendOffsetsToTransaction(
                offsets,
                inputMetadata.consumerGroupId
            )

            Unit
        }
    }

    private fun waitForAll(
        futures: Iterable<ListenableFuture<*>>
    ) {
        try {
            futures.forEach { future ->
                future.get()
            }
        } catch (exception: ExecutionException) {
            /*
             * Expose the real Kafka send failure instead of only
             * the Future wrapper exception.
             */
            throw exception.cause ?: exception
        }
    }

    private fun eventsTopic(pair: Pair ): String =
        "events_${pair.leftSideName}_${pair.rightSideName}"

    private fun tradesTopic(pair: Pair): String =
        "trades_${pair.leftSideName}_${pair.rightSideName}"

    private fun pairKey(pair: Pair): String =
        "${pair.leftSideName}_${pair.rightSideName}"

    companion object {
        private const val ORDER_BOOK_CHANGELOG_TOPIC =
            "orderbook_changelog"
    }
}